camel.main.routes-include-pattern=routes/yaml/*.yaml
quarkus.camel.xslt.sources=xslt/persons-transform.xsl
aviationstack.api.key=55785c84085ce06af91141a32d60a747
quarkus.http.host=localhost
quarkus.http.port=8080
backend.person.soap.url=http://localhost:8085/services/person/v2
quarkus.log.level=INFO
quarkus.log.console.level=INFO

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."person-xml-input".level=INFO
quarkus.log.category."person-json-before-backend".level=INFO
quarkus.log.category."person-backend-call".level=INFO
quarkus.log.category."person-backend-response".level=INFO

# Optional: reduce noisy startup route dump logs
quarkus.log.category."org.apache.camel.main.RoutesConfigurer".level=WARN
quarkus.log.category."org.apache.camel.impl.engine.AbstractCamelContext".level=WARN
